name: Test TSX bug privatenumber/tsx#596 - https://github.com/privatenumber/tsx/issues/596

on:
  # Runs on pushes targeting the default branch
  # Uncomment next 2 lines to activate
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Main job
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: pnpm

      - name: Install dependencies
        run: pnpm i

      - name: Run check command to check for `tsx-0`
        run: pnpm run check

      - name: Also run `ls` just to make sure
        run: ls
